<?php

/**
 * @file
 * Primary module hooks for chatbot module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_theme().
 */
function chatbot_theme($existing, $type, $theme, $path) {
  return [
    'chatbot' => [
      'template' => 'cfc-chatbot',
      'variables' => [
        'variables' => [
          'chatbot_title' => NULL,
          'chatbot_logo' => NULL,
        ],
      ],
    ],
  ];
}

/**
 * Implements hook_help().
 */
function chatbot_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.chatbot':
      $text = file_get_contents(__DIR__ . '/README.md');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . Html::escape($text) . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}
